const apiData = {
  name: "harrison mweene",
  age: "23",
  phone: "0973751049",
  nrc: "449946/10/1",
  address: "garden compound lusaka",
  witness_name: "john doe",
  witness_age: "33",
  witness_phone: "0773411223",
  witness_nrc: "355122/15/1",
  witness_address: "garden",
  location: "10 miles mungule",
  site_name: "b",
  plot_size: "40 x 20",
  plot_number: "2b",
  price: "12000",
  amount_paid: "6000",
  balance: "6000",
  date_bought: "2025-11-13",
  letter_of_sale: "https://api-docs.deepseek.com/quick_start/pricing/",
  authorization_letter: "https://api-docs.deepseek.com/quick_start/pricing/",
  agreement_form: "https://api-docs.deepseek.com/quick_start/pricing/",
  allocation_form: "https://api-docs.deepseek.com/quick_start/pricing/",
  document_nrc: "https://api-docs.deepseek.com/quick_start/pricing/",
};
